import type { RestaurantDetail } from "@/types/restaurant";

export const restaurantDetails: Record<string, RestaurantDetail> = {
  "sakura-house": {
    slug: "sakura-house",
    name: "Sakura House",
    icon: "fish",
    coverFrom: "#FEF3C7",
    coverTo: "#FDE68A",
    rating: 4.8,
    reviewCount: 640,
    deliveryTime: "25 min",
    distance: "1.8 km",
    deliveryFee: "$1.99",
    isOpen: true,
    address: "12 Maple Street, Downtown",
    description:
      "Authentic Japanese kitchen serving fresh sushi, ramen, and bento boxes made daily with quality ingredients.",
    categories: ["Popular", "Sushi", "Ramen", "Sides", "Drinks"],
    openingHours: [
      { day: "Mon – Fri", hours: "11:00 AM – 10:00 PM" },
      { day: "Sat – Sun", hours: "12:00 PM – 11:00 PM" },
    ],
    menu: [
      {
        id: "salmon-nigiri-set",
        name: "Salmon Nigiri Set",
        description: "8 pieces of fresh salmon nigiri with wasabi and pickled ginger.",
        price: 23.0,
        icon: "fish",
        category: "Popular",
        gradientFrom: "#E0E7FF",
        gradientTo: "#C7D2FE",
        rating: 4.9,
        reviewCount: 214,
        ingredients: ["Salmon", "Sushi rice", "Wasabi", "Pickled ginger", "Nori"],
      },
      {
        id: "dragon-roll",
        name: "Dragon Roll",
        description: "Shrimp tempura roll topped with avocado and eel sauce.",
        price: 16.5,
        icon: "fish",
        category: "Sushi",
        gradientFrom: "#FCE7F3",
        gradientTo: "#FBCFE8",
        rating: 4.7,
        reviewCount: 132,
        ingredients: ["Shrimp tempura", "Avocado", "Eel sauce", "Sushi rice", "Sesame seeds"],
      },
      {
        id: "california-roll",
        name: "California Roll",
        description: "Crab, avocado, and cucumber, rolled in toasted sesame seeds.",
        price: 12.0,
        icon: "fish",
        category: "Sushi",
        gradientFrom: "#DBEAFE",
        gradientTo: "#BFDBFE",
        rating: 4.6,
        reviewCount: 98,
        ingredients: ["Crab", "Avocado", "Cucumber", "Sushi rice", "Sesame seeds"],
      },
      {
        id: "tonkotsu-ramen",
        name: "Tonkotsu Ramen",
        description: "Rich pork bone broth with chashu, egg, and scallions.",
        price: 15.0,
        icon: "soup",
        category: "Ramen",
        gradientFrom: "#FEF9C3",
        gradientTo: "#FDE68A",
        rating: 4.9,
        reviewCount: 301,
        ingredients: ["Pork bone broth", "Chashu pork", "Soft egg", "Noodles", "Scallions"],
      },
      {
        id: "spicy-miso-ramen",
        name: "Spicy Miso Ramen",
        description: "Miso broth with a chili kick, corn, and bamboo shoots.",
        price: 15.5,
        icon: "soup",
        category: "Ramen",
        gradientFrom: "#FFE4E6",
        gradientTo: "#FECDD3",
        rating: 4.7,
        reviewCount: 156,
        ingredients: ["Miso broth", "Chili oil", "Corn", "Bamboo shoots", "Noodles"],
      },
      {
        id: "edamame",
        name: "Edamame",
        description: "Steamed soybeans with sea salt.",
        price: 5.5,
        icon: "salad",
        category: "Sides",
        gradientFrom: "#DCFCE7",
        gradientTo: "#BBF7D0",
        rating: 4.5,
        reviewCount: 64,
        ingredients: ["Soybeans", "Sea salt"],
      },
      {
        id: "miso-soup",
        name: "Miso Soup",
        description: "Traditional soybean paste soup with tofu and seaweed.",
        price: 4.0,
        icon: "soup",
        category: "Sides",
        gradientFrom: "#F1F5F9",
        gradientTo: "#E2E8F0",
        rating: 4.4,
        reviewCount: 51,
        ingredients: ["Miso paste", "Tofu", "Seaweed", "Dashi broth", "Scallions"],
      },
      {
        id: "green-tea",
        name: "Iced Green Tea",
        description: "Chilled Japanese green tea, unsweetened.",
        price: 3.5,
        icon: "drink",
        category: "Drinks",
        gradientFrom: "#DCFCE7",
        gradientTo: "#BBF7D0",
        rating: 4.6,
        reviewCount: 40,
        ingredients: ["Green tea leaves", "Water", "Ice"],
      },
    ],
  },

  "bun-and-co": {
    slug: "bun-and-co",
    name: "Bun & Co.",
    icon: "beef",
    coverFrom: "#DBEAFE",
    coverTo: "#BFDBFE",
    rating: 4.6,
    reviewCount: 410,
    deliveryTime: "18 min",
    distance: "0.9 km",
    deliveryFee: "Free",
    isOpen: true,
    address: "88 Baker Avenue, Midtown",
    description:
      "Smash burgers, crispy fries, and thick milkshakes. A neighborhood favorite since day one.",
    categories: ["Popular", "Burgers", "Sides", "Drinks"],
    openingHours: [{ day: "Mon – Sun", hours: "10:00 AM – 11:30 PM" }],
    menu: [
      {
        id: "classic-cheeseburger",
        name: "Classic Cheeseburger",
        description: "Beef patty, cheddar, lettuce, tomato, and house sauce.",
        price: 11.5,
        icon: "beef",
        category: "Popular",
        gradientFrom: "#FEF3C7",
        gradientTo: "#FDE68A",
        rating: 4.7,
        reviewCount: 188,
        ingredients: ["Beef patty", "Cheddar cheese", "Lettuce", "Tomato", "Brioche bun", "House sauce"],
      },
      {
        id: "double-smash",
        name: "Double Smash",
        description: "Two smashed beef patties with caramelized onions.",
        price: 14.0,
        icon: "beef",
        category: "Burgers",
        gradientFrom: "#FFE4E6",
        gradientTo: "#FECDD3",
        rating: 4.8,
        reviewCount: 172,
        ingredients: ["Two beef patties", "Caramelized onions", "American cheese", "Brioche bun"],
      },
      {
        id: "crispy-chicken-burger",
        name: "Crispy Chicken Burger",
        description: "Buttermilk fried chicken with spicy mayo and pickles.",
        price: 12.5,
        icon: "drumstick",
        category: "Burgers",
        gradientFrom: "#FEF9C3",
        gradientTo: "#FDE68A",
        rating: 4.6,
        reviewCount: 140,
        ingredients: ["Buttermilk fried chicken", "Spicy mayo", "Pickles", "Brioche bun"],
      },
      {
        id: "loaded-fries",
        name: "Loaded Fries",
        description: "Crispy fries topped with cheese sauce and bacon bits.",
        price: 8.0,
        icon: "default",
        category: "Sides",
        gradientFrom: "#FEF3C7",
        gradientTo: "#FDE68A",
        rating: 4.5,
        reviewCount: 96,
        ingredients: ["Potato fries", "Cheese sauce", "Bacon bits", "Scallions"],
      },
      {
        id: "onion-rings",
        name: "Onion Rings",
        description: "Beer-battered onion rings with dipping sauce.",
        price: 6.5,
        icon: "default",
        category: "Sides",
        gradientFrom: "#DCFCE7",
        gradientTo: "#BBF7D0",
        rating: 4.3,
        reviewCount: 58,
        ingredients: ["Onions", "Beer batter", "Dipping sauce"],
      },
      {
        id: "chocolate-shake",
        name: "Chocolate Milkshake",
        description: "Thick and creamy, topped with whipped cream.",
        price: 6.0,
        icon: "drink",
        category: "Drinks",
        gradientFrom: "#E0E7FF",
        gradientTo: "#C7D2FE",
        rating: 4.7,
        reviewCount: 84,
        ingredients: ["Milk", "Chocolate syrup", "Vanilla ice cream", "Whipped cream"],
      },
    ],
  },

  "green-bowl": {
    slug: "green-bowl",
    name: "Green Bowl",
    icon: "salad",
    coverFrom: "#DCFCE7",
    coverTo: "#BBF7D0",
    rating: 4.9,
    reviewCount: 512,
    deliveryTime: "22 min",
    distance: "2.4 km",
    deliveryFee: "$2.49",
    isOpen: true,
    address: "5 Garden Lane, Uptown",
    description:
      "Fresh salads, grain bowls, and smoothies. Healthy food that doesn't compromise on flavor.",
    categories: ["Popular", "Bowls", "Salads", "Drinks"],
    openingHours: [
      { day: "Mon – Sat", hours: "9:00 AM – 9:00 PM" },
      { day: "Sun", hours: "10:00 AM – 6:00 PM" },
    ],
    menu: [
      {
        id: "quinoa-power-bowl",
        name: "Quinoa Power Bowl",
        description: "Quinoa, roasted chickpeas, avocado, and tahini dressing.",
        price: 13.5,
        icon: "salad",
        category: "Popular",
        gradientFrom: "#DCFCE7",
        gradientTo: "#BBF7D0",
        rating: 4.9,
        reviewCount: 176,
        ingredients: ["Quinoa", "Roasted chickpeas", "Avocado", "Cherry tomatoes", "Tahini dressing"],
      },
      {
        id: "grilled-chicken-bowl",
        name: "Grilled Chicken Bowl",
        description: "Grilled chicken, brown rice, greens, and lemon vinaigrette.",
        price: 14.5,
        icon: "drumstick",
        category: "Bowls",
        gradientFrom: "#FEF9C3",
        gradientTo: "#FDE68A",
        rating: 4.7,
        reviewCount: 121,
        ingredients: ["Grilled chicken", "Brown rice", "Mixed greens", "Lemon vinaigrette"],
      },
      {
        id: "salmon-bowl",
        name: "Seared Salmon Bowl",
        description: "Seared salmon, sweet potato, kale, and miso dressing.",
        price: 16.0,
        icon: "fish",
        category: "Bowls",
        gradientFrom: "#E0E7FF",
        gradientTo: "#C7D2FE",
        rating: 4.9,
        reviewCount: 143,
        ingredients: ["Seared salmon", "Sweet potato", "Kale", "Miso dressing", "Sesame seeds"],
      },
      {
        id: "caesar-salad",
        name: "Classic Caesar Salad",
        description: "Romaine, parmesan, croutons, and house Caesar dressing.",
        price: 10.5,
        icon: "salad",
        category: "Salads",
        gradientFrom: "#DCFCE7",
        gradientTo: "#BBF7D0",
        rating: 4.5,
        reviewCount: 89,
        ingredients: ["Romaine lettuce", "Parmesan", "Croutons", "Caesar dressing"],
      },
      {
        id: "berry-smoothie",
        name: "Mixed Berry Smoothie",
        description: "Strawberry, blueberry, banana, and almond milk.",
        price: 6.5,
        icon: "drink",
        category: "Drinks",
        gradientFrom: "#FFE4E6",
        gradientTo: "#FECDD3",
        rating: 4.8,
        reviewCount: 77,
        ingredients: ["Strawberry", "Blueberry", "Banana", "Almond milk"],
      },
    ],
  },
};

export function getRestaurantBySlug(slug: string) {
  return restaurantDetails[slug] ?? null;
}

export function getAllRestaurantSlugs() {
  return Object.keys(restaurantDetails);
}
